force-app/main/default/objects/SQX_Part__c/SQX_Part__c.object-meta.xml
<CustomObject>
    <description>This is to Record the Parts</description>
    <label>Part</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Part__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to define the Part is Active or Not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SQX_Part__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <description>This is field is to store the Part Number</description>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/partSyncScheduleBatchTest.cls
@isTest
public class partSyncScheduleBatchTest {

    @isTest
    public static void testScheduledBatchRuns() {
        SQX_Part__c testPart = new SQX_Part__c(
            Name = 'ScheduledPart',
            Part_Number__c = 'P123',
            Active__c = true
        );
        insert testPart;

        Test.startTest();
        String cronExp = '0 0 0 1 1 ? 2050';
        System.schedule('Test Scheduled Part Sync', cronExp, new partSyncScheduleBatch());
        Test.stopTest();

       
    }
}